#!/usr/bin/env bash

set -e

source .github/scripts/metrics-helper.sh
source .github/scripts/rca-engine.sh

# ==========================================
# Parse issue title
# ==========================================

TITLE="$ISSUE_TITLE"

SITE=$(echo "$TITLE" \
  | sed -E 's/ is down.*//' \
  | sed -E 's/^🟥 //g' \
  | sed -E 's/^🛑 //g' \
  | xargs)

echo "Detected site: $SITE"

# ==========================================
# Fetch metrics
# ==========================================

SLUG=$(get_slug "$SITE")

SITE_URL=$(get_site_url "$SITE")

LATENCY=$(get_latency "$SLUG")

UPTIME=$(get_uptime "$SITE")

# ==========================================
# Increment incidents FIRST
# ==========================================

increment_incidents "$SLUG"

INCIDENTS=$(get_incidents "$SLUG")

store_outage_start "$SLUG"

MTTR=$(get_mttr "$SLUG")

# ==========================================
# URLs
# ==========================================

INCIDENT_URL="$INCIDENT_BASE_URL/$ISSUE_NUMBER"

STATUS_URL="$STATUS_BASE_URL/$SLUG"

GITHUB_ISSUE_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}"

# ==========================================
# Generate RCA
# ==========================================

generate_rca "$SITE" "$LATENCY"

# ==========================================
# Environment detection
# ==========================================

ENVIRONMENT="Production"

LOWER=$(echo "$SITE" | tr '[:upper:]' '[:lower:]')

if [[ "$LOWER" =~ test|debug|sandbox|staging|dev ]]; then
  ENVIRONMENT="Testing / Staging"
fi

# ==========================================
# Health classification
# ==========================================

HEALTH="Stable"

# ==========================================
# Speed ladder
# ==========================================

SPEED="⚪ Unknown"

if [[ "$LATENCY" =~ ^[0-9]+$ ]]; then

  if [ "$LATENCY" -lt 100 ]; then

    SPEED="🚀 Excellent"

  elif [ "$LATENCY" -lt 300 ]; then

    SPEED="⚡ Fast"

  elif [ "$LATENCY" -lt 700 ]; then

    SPEED="🏎️ Responsive"

  elif [ "$LATENCY" -lt 1500 ]; then

    SPEED="🚗 Moderate"

  elif [ "$LATENCY" -lt 3000 ]; then

    SPEED="🐢 Slow"

  else

    SPEED="🐌 Severely Degraded"

  fi

  # ========================================
  # Health state
  # ========================================

  if [ "$LATENCY" -gt 3000 ]; then

    HEALTH="Severely Degraded"

  elif [ "$LATENCY" -gt 1500 ]; then

    HEALTH="Degraded"

  elif [ "$LATENCY" -gt 700 ]; then

    HEALTH="Elevated Latency"

  fi
fi

# ==========================================
# Flapping detection
# ==========================================

FLAP_WARNING=""

LAST_DOWN=$(jq -r \
  --arg slug "$SLUG" \
  '.[$slug].last_down // 0' \
  observability/incident-metrics.json)

NOW=$(date +%s)

if [ "$LAST_DOWN" -gt 0 ]; then

  GAP=$((NOW - LAST_DOWN))

  if [ "$GAP" -lt 7200 ]; then

    FLAP_WARNING="⚠️ Repeated instability detected in recent monitoring window."

  fi
fi

# ==========================================
# Time block
# ==========================================

LOCAL_TIME=$(TZ="$SUMMARY_TIMEZONE" \
  date +"%d %b %Y | %I:%M %p")

UTC_TIME=$(date -u +"%H:%M UTC")

# ==========================================
# Build Telegram message
# ==========================================

MESSAGE="🚨 Incident Detected | #️⃣ Incident: #$ISSUE_NUMBER

📡 Status: DOWN | 🧪 Environment: $ENVIRONMENT
🌐 Site: $SITE | 🔗 : $SITE_URL

📈 Uptime: $UPTIME
📊 Health: $HEALTH
⚡ Response Time: $LATENCY ms
🚦 Speed Class: $SPEED
📉 Incident Count: $INCIDENTS
📘 Avg MTTR: $MTTR mins

----------------------------------
🛠 Probable Cause:
$RCA

🔍 Suggested Checks:
$CHECKS

⏳ ETA: $ETA

⚠️ : $FLAP_WARNING
-----------------------------------

🔗 : $STATUS_URL

🛠 : $GITHUB_ISSUE_URL

📄 : $INCIDENT_URL

🕒 $LOCAL_TIME | 🌍 $UTC_TIME"

echo "$MESSAGE"

# ==========================================
# Send Telegram
# ==========================================

.github/scripts/tg-send.sh "$MESSAGE"

# ==========================================
# GitHub comment
# ==========================================

COMMENT="## 🚨 Automated Incident Analysis

### 🌐 Service Information

| Metric | Value |
|---|---|
| Site | $SITE |
| Endpoint | $SITE_URL |
| Severity | $SEVERITY |
| Environment | $ENVIRONMENT |
| Health | $HEALTH |
| Response Time | $LATENCY ms |
| Speed Class | $SPEED |
| Incident Count | $INCIDENTS |
| Avg MTTR | $MTTR mins |

### 🛠 Probable Cause

$RCA

### 🔍 Suggested Checks

$CHECKS

### ⏳ Estimated Recovery

$ETA

### ⚠️ Stability Signals

$FLAP_WARNING

### 🔗 References

- Status Dashboard: $STATUS_URL
- GitHub Incident: $GITHUB_ISSUE_URL
- Incident Archive: $INCIDENT_URL

---

<sub>🤖 Automated RCA generated by Sumit's Observability Stack  
Maintainer: Sumit-SC • Alerts via [Upptime-Alerts-Tracker](https://t.me/mitSutestBot)
• Powered by [Upptime](upptime.js.org) + [GitHub Actions](https://github.com/features/actions)</sub>
---

# ==========================================
# Post GitHub comment
# ==========================================

.github/scripts/issue-comment.sh "$
