#!/usr/bin/env bash

set -e

source .github/scripts/metrics-helper.sh

# ==========================================
# Parse issue title
# ==========================================

TITLE="$ISSUE_TITLE"

SITE=$(echo "$TITLE" \
  | sed -E 's/ is up.*//' \
  | sed -E 's/^🟩 //g' \
  | xargs)

echo "Recovered site: $SITE"

# ==========================================
# Fetch metrics
# ==========================================

SLUG=$(get_slug "$SITE")

LATENCY=$(get_latency "$SLUG")

UPTIME=$(get_uptime "$SITE")

INCIDENTS=$(get_incidents "$SLUG")

MTTR=$(calculate_mttr "$SLUG")

# ==========================================
# URLs
# ==========================================

INCIDENT_URL="$INCIDENT_BASE_URL/$ISSUE_NUMBER"

STATUS_URL="$STATUS_BASE_URL/$SLUG"

# ==========================================
# Downtime classification
# ==========================================

DOWNTIME_MIN=$((MTTR / 60))

RECOVERY_STATE="Stable"

RECOVERY_NOTE="Temporary instability resolved automatically."

if [ "$MTTR" -gt 3600 ]; then

  RECOVERY_STATE="Recovered After Extended Outage"

  RECOVERY_NOTE="Extended outage recovered successfully.

Possible contributing factors:
• infrastructure restart
• provider instability
• DNS propagation
• backend recovery"

elif [ "$MTTR" -gt 900 ]; then

  RECOVERY_STATE="Recovered After Major Degradation"

  RECOVERY_NOTE="Temporary service instability resolved automatically."

elif [ "$MTTR" -gt 300 ]; then

  RECOVERY_STATE="Recovered After Moderate Instability"

  RECOVERY_NOTE="Moderate service degradation resolved successfully."

else

  RECOVERY_STATE="Stable"

  RECOVERY_NOTE="Transient outage auto-resolved."

fi

# ==========================================
# Health classification
# ==========================================

HEALTH="Healthy"

if [ "$LATENCY" != "unknown" ]; then

  if [ "$LATENCY" -gt 2500 ]; then
    HEALTH="Still Degraded"
  elif [ "$LATENCY" -gt 1000 ]; then
    HEALTH="Partially Stabilized"
  elif [ "$LATENCY" -gt 500 ]; then
    HEALTH="Elevated Latency"
  fi
fi

# ==========================================
# Time block
# ==========================================

LOCAL_TIME=$(TZ="$SUMMARY_TIMEZONE" \
  date +"%d %b %Y | %I:%M %p")

UTC_TIME=$(date -u +"%H:%M UTC")

# ==========================================
# Telegram recovery message
# ==========================================

MESSAGE="🟢 Incident Resolved

🌐 Site: $SITE
📡 Status: HEALTHY
📈 Uptime: $UPTIME
📊 Recovery State: $RECOVERY_STATE
📊 Health: $HEALTH
⚡ Current Latency: $LATENCY ms
📉 Incident Count: $INCIDENTS
📘 MTTR: $DOWNTIME_MIN mins
⏱ Downtime: $DOWNTIME_MIN mins

🛠 Recovery Notes:
$RECOVERY_NOTE

🔗 Incident:
$INCIDENT_URL

🔗 Status:
$STATUS_URL

🕒 $LOCAL_TIME | 🌍 $UTC_TIME"

echo "$MESSAGE"

# ==========================================
# Send Telegram recovery
# ==========================================

.github/scripts/tg-send.sh "$MESSAGE"

# ==========================================
# Recovery GitHub comment
# ==========================================

COMMENT="## 🟢 Automated Recovery Analysis

| Metric | Value |
|---|---|
| Status | HEALTHY |
| Recovery State | $RECOVERY_STATE |
| Health | $HEALTH |
| Current Latency | $LATENCY ms |
| Incident Count | $INCIDENTS |
| MTTR | $DOWNTIME_MIN mins |
| Downtime | $DOWNTIME_MIN mins |

### 🛠 Recovery Summary

$RECOVERY_NOTE

### 📊 Operational Notes

• Infrastructure recovered successfully
• Monitoring post-recovery latency stability
• Observability checks resumed normally

### 🔗 References

- Incident Page: $INCIDENT_URL
- Status Page: $STATUS_URL

---

<sub>
🟢 Automated recovery analysis generated by Sumit Observability Stack  
Powered by Upptime + GitHub Actions
</sub>"

.github/scripts/issue-comment.sh "$COMMENT"

# ==========================================
# Add resolved label
# ==========================================

gh issue edit "$ISSUE_NUMBER" \
  --add-label "resolved" || true
