#!/usr/bin/env bash

set -e

source .github/scripts/metrics-helper.sh
source .github/scripts/rca-engine.sh

# ==========================================
# Parse issue title
# ==========================================

TITLE="$ISSUE_TITLE"

SITE=$(echo "$TITLE" \
  | sed -E 's/ is down.*//' \
  | sed -E 's/ is up.*//' \
  | sed -E 's/^🟥 //g' \
  | sed -E 's/^🟩 //g' \
  | sed -E 's/^🛑 //g' \
  | xargs)

echo "Detected site: $SITE"

# ==========================================
# Fetch metrics
# ==========================================

SLUG=$(get_slug "$SITE")

LATENCY=$(get_latency "$SLUG")

UPTIME=$(get_uptime "$SITE")

SITE_URL=$(get_site_url "$SITE")

INCIDENTS=$(get_incidents "$SLUG")

MTTR=$(get_mttr "$SLUG")

# ==========================================
# Generate RCA
# ==========================================

generate_rca "$SITE" "$LATENCY"

# ==========================================
# Environment detection
# ==========================================

ENVIRONMENT="Production"

LOWER=$(echo "$SITE" | tr '[:upper:]' '[:lower:]')

if [[ "$LOWER" =~ test|debug|sandbox|staging|dev ]]; then
  ENVIRONMENT="Testing / Staging"
fi

# ==========================================
# URLs
# ==========================================

INCIDENT_URL="$INCIDENT_BASE_URL/$ISSUE_NUMBER"

STATUS_URL="$STATUS_BASE_URL/$SLUG"

GITHUB_ISSUE_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}"


# ==========================================
# Health classification
# ==========================================

HEALTH="Stable"

if [ "$LATENCY" != "unknown" ]; then

  if [ "$LATENCY" -gt 3000 ]; then
    HEALTH="Severely Degraded"
  elif [ "$LATENCY" -gt 1500 ]; then
    HEALTH="Degraded"
  elif [ "$LATENCY" -gt 700 ]; then
    HEALTH="Elevated Latency"
  fi
fi

# ==========================================
# Time block
# ==========================================

LOCAL_TIME=$(TZ="$SUMMARY_TIMEZONE" \
  date +"%d %b %Y | %I:%M %p")

UTC_TIME=$(date -u +"%H:%M UTC")

# ==========================================
# Build Telegram message
# ==========================================

MESSAGE="🚨 Incident Detected

🌐 Site: $SITE |🔗 : $SITE_URL
🧪 Environment: $ENVIRONMENT
📡 Status: DOWN
📈 Uptime: $UPTIME
📊 Health: $HEALTH
⚡ Response Time: $LATENCY ms
📉 Incident Count: $INCIDENTS
📘 MTTR: $MTTR mins
#️⃣ Incident: #$ISSUE_NUMBER

🛠 Probable Cause:
$RCA

🔍 Suggested Checks:
$CHECKS

⏳ ETA:
$ETA

🔗 Status Dashboard:
$STATUS_URL

🛠 Incident Report:
$GITHUB_ISSUE_URL

📄 Incident Archive:
$INCIDENT_URL


🕒 $LOCAL_TIME | 🌍 $UTC_TIME"

echo "$MESSAGE"

# ==========================================
# Send Telegram
# ==========================================

.github/scripts/tg-send.sh "$MESSAGE"

# ==========================================
# GitHub comment
# ==========================================

COMMENT="## 🚨 Automated Incident Analysis

🌐 Site: $SITE |🔗 Endpoint: $SITE_URL 


| Metric | Value |
|---|---|
| Severity | $SEVERITY |
| Environment | $ENVIRONMENT |
| Health | $HEALTH |
| Response Time | $LATENCY ms |
| Incident Count | $INCIDENTS |
| MTTR | $MTTR mins |

### 🛠 Probable Cause
$RCA

### 🔍 Suggested Checks
$CHECKS

### ⏳ Estimated Recovery
$ETA

### 🔗 References 
- Incident Page: $INCIDENT_URL 
- Status Page: $STATUS_URL

---
<sub>🤖 Automated RCA generated by Sumit's Observability Stack  
Maintainer: Sumit-SC • Alerts via [Upptime-Alerts-Tracker](https://t.me/mitSutestBot)
• Powered by [Upptime](upptime.js.org) + [GitHub Actions](https://github.com/features/actions)</sub>
---

.github/scripts/issue-comment.sh "$COMMENT"
