# ==========================================
# UPPTIME CONFIGURATION
# ==========================================
#
# Main configuration file for:
# - uptime monitoring
# - status website generation
# - README generation
# - GitHub Actions workflows
#
# File:
# .upptimerc.yml
#
# ==========================================

# ==========================================
# Repository owner + repo name
# ==========================================
# Change these first
owner: Sumit-SC # Your GitHub organization or username, where this repository lives
repo: ping # The name of this repository

# Add this section to change the frequency
workflow-schedule:
  uptime: "*/15 * * * *"

# # Global settings (applies to all sites)
# user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# ==========================================
# Sites to monitor Configuration
# Pattern to follow only need name & url if u want to add logo say site does not have favicon can do that 
# - name: Page
#   url: https://xyz.com
#   icon: https://i.ibb.co/abc.png
#   type: globalping # https://upptime.js.org/docs/configuration/#globalping
#   location: california # Location to run the check from. Optional. Default is "World"
#   method: GET  # Force GET request (HEAD is often blocked) [optional]
#   headers: #[Optional]
#     - "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
#     - "Accept-Language: en-US,en;q=0.5"
#     - "Cache-Control: no-cache"
#     - "Pragma: no-cache"
#   assignees: # Users to assign downtime issues automatically if sites goes down & ping them (optional)
#     - @gitname
# ==========================================
#   Secret URLs#
#   If you don't want to show a URL publicly, you can use repository secrets 
#   (see Creating and storing encrypted secrets). Instead of the plain text URL, 
#   add the name of the secret prefixed with a $ character:
#   - name: Secret Site
#     url: $SECRET_SITE
# ==========================================
sites:
  - name: Portfolio Page
    url: https://sumit-sc.github.io
    type: globalping
    location: india # Location to run the check from. Optional. Default is "World"
    icon: https://i.ibb.co/ZpH1RStQ/business-1991029.png
  - name: Personal-Lab
    url: http://www.colab.indevs.in
    icon: https://i.ibb.co/k6GgHg8J/photo-2026-02-13-17-47-19.jpg
  - name: Portfolio Website
    url: https://www.sumit.indevs.in
    icon: https://i.ibb.co/yF29Pd46/icon.png
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Streamio
    url: https://idx.theworkpc.com
    icon: https://i.postimg.cc/XqWnmDXr/Picsart-25-10-09-08-09-45-867.png
    
  # # Offline Site to test for outage alert-checks
  # - name: Test-Shopping
  #   url: https//Shopping.com
  # - name: Debug-app
  #   url: https://example.koj.co
  - name: my-web
    url: test.com
  - name: Debug-Test
    url: https://example.invalid
  # - name: amaosn
  #   url: https://abc.amason
  
  #
# ==========================================
# Status website configuration read here https://upptime.js.org/docs/configuration/#status-website
# # Basic config (name & url rest are optional params if it fails try adding baseUrl: & navbar for navigation pages)
# status-website:
#  cname: xyz.abc.com (optional - will take github io page if not given any custom domian to host the pages)
#  name: some name for stats page
#  logo: url for page logo
# # Custom status website theme Available themes are light, dark, night or ocean. 
#  theme: ocean # default to dark if not mentioned or commented
#  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages.
# # https://upptime.js.org/docs/configuration/#intro-text
#  navbar: # optional https://upptime.js.org/docs/configuration/#navbar-links
#    - title: Status
#      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO
# ==========================================
    
status-website:
  # 1. Your custom domain
  cname: status.sumit.indevs.in # Custom domain CNAME
  # 2. MUST be / when using a custom domain or # baseUrl: /repo
  baseUrl:    
  # 3. Naming, Logo, theme, intro and navbar 
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Sumit's Portfolio | Service Status" # Status website title
  theme: night
  introTitle: "**Service Status** for my web applications, powered by Upptime and a status page, powered entirely by GitHub."
  # introMessage: This page monitors the uptime and response time of my portfolio and core services.
  introMessage: |
    • This page monitors the uptime and response time of my portfolio and core services.
    Real-time infrastructure monitoring powered by:
    - Upptime
    - GitHub Actions
    - Telegram alerting
    - Observability analytics
  
  navbar: # 4 is the safe point or the page ui distorts if titles are large 
    - title: Portfolio Website
      href: https://www.sumit.indevs.in
    - title: Server Stats
      href: https://telemetry.indevs.in
    - title: WebPages Monitor
      href: https://sumit.betteruptime.com
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO
    # - title: Upp-time 
    #   href: https://upptime.js.org/
    #   # This is the subtitle that appears below the name
    #   sub: Build your own website tracker
    - title: Upp-time
      href: https://upptime.js.org/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration & https://upptime.js.org/docs/configuration/#repository-metadata
# Advanced monitoring frequency (optional)
# commitMessages:
# readmeTick: ":green_heart: Update uptime [skip ci]"
# ==========================================
# Commit messages
# ==========================================

# commitMessages:

#   commitAuthorName: "observability-bot & Upptime Bot"

#   commitAuthorEmail: "mitsu@duck.com" # "actions@github.com, mitsu@duck.com & upptime@koj.co"

#   readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
#   summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
#   summary: "📊 Update infrastructure summary"
#   statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
#   graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"


# ==========================================
# Advanced monitoring settings https://upptime.js.org/docs/configuration/#internationalization
# ==========================================

# i18n:

#   activeIncidents: Active Incidents

#   allSystemsOperational: All systems operational

#   incidentReport: Incident Report

#   activeIncidentSummary: |
#     Opened at {{date}}
#     with {{upptime}}

# ==========================================
# Response time chart settings https://upptime.js.org/docs/configuration/#repository-metadata 
# By default they are false so no need to add them in below config unless u want to toggle them manually.
# ==========================================

# skipDescriptionUpdate: false

# skipTopicsUpdate: false

# skipHomepageUpdate: false

# skipStatusWebsiteUpdate: false

# skipReadme: false

# skipGraphs: false

# ==========================================
# CUSTOM OBSERVABILITY NOTES
# ==========================================
#
# Your custom workflows:
#
# - summary.yml
# - latency-alerts.yml
# - incident-alerts.yml
#
# are separate from Upptime core.
#
# Keep custom logic inside:
#
# observability/
#
# NOT history/
#

# ==========================================
# README TEMPLATE SUPPORT
# ==========================================
#
# IMPORTANT:
# Create:
#
# README.tpl
#
# So Upptime does NOT erase
# your custom README sections.
#
# ==========================================

