name: Telegram Alerts (Upptime)

on:
  issues:
    types: [opened, closed]

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - name: Filter Upptime issues
        id: filter
        run: |
          TITLE="${{ github.event.issue.title }}"

          if [[ "$TITLE" == *"is down"* ]] || [[ "$TITLE" == *"is up"* ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if not relevant
        if: steps.filter.outputs.valid != 'true'
        run: exit 0

      - name: Build message
        id: build
        env:
          INCIDENT_BASE_URL: ${{ secrets.INCIDENT_BASE_URL }}
        run: |
          TITLE="${{ github.event.issue.title }}"
          NUMBER="${{ github.event.issue.number }}"
          ACTION="${{ github.event.action }}"

          INCIDENT_URL="$INCIDENT_BASE_URL/$NUMBER"
          # URL="${{ github.event.issue.html_url }}"

          # =========================
          # 🚨 INCIDENT OPENED (DOWN)
          # =========================
          if [[ "$TITLE" == *"is down"* ]]; then
            STATUS="DOWN"
            ICON="🛑"
            ALERT="🚨 INCIDENT"
          else
            STATUS="RECOVERED"
            ICON="🟢"
            ALERT="✅ RESOLVED"
          fi

          SITE=$(echo "$TITLE" | sed 's/ is down.*//; s/ is up.*//')

          MSG="$ICON $ALERT\n\n"
          MSG+="🌐 Site: $SITE\n"
          MSG+="📡 Status: $STATUS\n"
          MSG+="🔗 $URL\n\n"
          MSG+="🕒 $(TZ='Asia/Kolkata' date +"%d %b %Y | %I:%M %p IST")"

          echo "msg<<EOF" >> $GITHUB_OUTPUT
          echo -e "$MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Telegram
        run: |
          PAYLOAD=$(jq -n \
            --arg chat_id "${{ secrets.CHAT_ID }}" \
            --arg text "${{ steps.build.outputs.msg }}" \
            --argjson thread_id ${{ secrets.ALERTS_TOPIC_ID }} \
            '{
              chat_id: $chat_id,
              message_thread_id: $thread_id,
              text: $text,
              disable_web_page_preview: true
            }')

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.SUMMARY_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
